using tests
using unit

namespace tests {
  class CompilerTest : Test {
    override void run() {
      using skew
      rename(compactWhitespace(input))
      var log = Log()
      var global = compile(log, [Source("<stdin>", input)])
      var output = log.toString()
      expectString(trim(expected), trim(output))
    }

    private {
      string input
      string expected
    }
  }

  bool isSpace(int c) {
    return c == ' ' || c == '\n'
  }

  string trim(string text) {
    var length = text.size()
    var start = 0
    var end = length
    while (start < length && isSpace(text[start])) {
      start++
    }
    while (start < end && isSpace(text[end - 1])) {
      end--
    }
    return text.slice(start, end)
  }

  string compactWhitespace(string text) {
    var wasSpace = false
    var result = ""
    for (var i = 0; i < text.size(); i++) {
      if (!isSpace(text[i])) {
        result += text.sliceCodeUnit(i)
        wasSpace = false
      } else if (!wasSpace) {
        result += " "
        wasSpace = true
      }
    }
    return result
  }

  CompilerTest test(string input, string expected) {
    return CompilerTest(trim(input), expected)
  }
}

@EntryPoint
int start() {
  tests.testSimple()

  var report = TerminalReport()
  Test.runAll(report)
  return report.failedCount()
}
