namespace Timestamp {
  def seconds double

  if TARGET == .JAVASCRIPT {
    def seconds double {
      return (dynamic.typeof(dynamic.performance) != "undefined" && dynamic.performance.now ? dynamic.performance.now() : dynamic.Date.now()) / 1000
    }
  }

  else if TARGET == .CSHARP {
    def seconds double {
      return dynamic.System.DateTime.Now.Ticks / (dynamic.System.TimeSpan.TicksPerSecond as double)
    }
  }
}
