namespace Skew.Tests {
  def testJavaScriptMinify {

# Strings should be emitted using the shortest representation
test("
@export
def main {
  dynamic.a(\"'\" + \"\\\"\")
}
", "
(function(){main=function(){a(\"'\"+'\"')}})();
").jsMinify

# Check for various whitespace issues
test("
@export
def main dynamic {
  dynamic.a(dynamic.b + +dynamic.c)
  dynamic.a(dynamic.b + -dynamic.c)
  dynamic.a(dynamic.b - +dynamic.c)
  dynamic.a(dynamic.b - -dynamic.c)
  return \"\"
  return dynamic.a
  return dynamic.a + dynamic.b
  return -dynamic.a
  return ~dynamic.a
  return !dynamic.a
  return []
  return {}
}
", "
(function(){main=function(){a(b+ +c);a(b+-c);a(b-+c);a(b- -c);return'';return a;return a+b;return-a;return~a;return!a;return[];return{}}})();
").jsMinify

# Check for whitespace with numeric literals
test("
@export
def foo dynamic {
  return -1
}

@export
def bar dynamic {
  return -1.5
}

@export
def baz dynamic {
  return 0
}
", "
(function(){foo=function(){return-1};bar=function(){return-1.5};baz=function(){return 0}})();
").jsMinify.foldAllConstants

# Check for omitting the leading zero
test("
@export
def foo dynamic {
  return [-1.5, -1.0, -0.5, -0.0, 0.0, 0.5, 1.0, 1.5]
}
", "
(function(){foo=function(){return[-1.5,-1,-.5,0,0,.5,1,1.5]}})();
").jsMinify.foldAllConstants

# There is no "dangling if" ambiguity here
test("
@export
def main {
  if dynamic.a() {
    if dynamic.b() {
      var c = dynamic.d()
      dynamic.e(c, c)
    } else {
      var f = dynamic.g()
      dynamic.h(f, f)
    }
  } else {
    dynamic.i()
  }
}
", "
(function(){main=function(){if(a()){if(b()){var c=d();e(c,c)}else{var f=g();h(f,f)}}else i()}})();
").jsMinify

# This must be careful about the "dangling if" ambiguity
test("
@export
def main {
  if dynamic.a() {
    if dynamic.b() {
      if dynamic.c() {
        var d = dynamic.e()
        dynamic.f(d, d)
      } else {
        var g = dynamic.h()
        dynamic.i(g, g)
      }
    }
  } else {
    dynamic.j()
  }
}
", "
(function(){main=function(){if(a()){if(b())if(c()){var d=e();f(d,d)}else{var g=h();i(g,g)}}else j()}})();
").jsMinify

# Another "dangling if" variant
test("
@export
def main {
  if dynamic.a() {
    if dynamic.b() {
      var c = dynamic.d()
      dynamic.e(c, c)
    } else if dynamic.f() {
      var g = dynamic.h()
      dynamic.i(g, g)
    }
  } else {
    var j = dynamic.k()
    dynamic.l(j, j)
  }
}
", "
(function(){main=function(){if(a()){if(b()){var c=d();e(c,c)}else if(f()){var g=h();i(g,g)}}else{var j=k();l(j,j)}}})();
").jsMinify

# A tricky "dangling if" issue
test("
@export
def main {
  if dynamic.a() {
    while true {
      if dynamic.b() { break }
    }
  } else {
    dynamic.c()
  }
}
", "
(function(){main=function(){if(a()){while(true)if(b())break}else c()}})();
").jsMinify

# Check that minification doesn't remove constants in switch statements unless necessary
test("
@export
const C = 2

@export
def main(x int, y Foo) {
  switch x {
    case C { dynamic.a() }
    case C + 3 { dynamic.a() }
  }
  switch y { case .FOO { dynamic.b() } }
}

enum Foo { FOO }
", "
(function(){main=function(x,y){switch(x){case C:a();break;case 5:a();break}switch(y){case Foo.FOO:b();break}};var Foo={FOO:0};C=2})();
").jsMinify

test("
@export
def foo string {
  return 0.toString
}
", "
(function(){foo=function(){return (0).toString()}})();
").jsMinify

# Make sure null is allowed to convert to string
test("
@export
def foo string {
  return null
}
", "
(function(){foo=function(){return null}})();
").jsMinify

# Avoid a space after "case" if possible
test("
@export
def main(x string) {
  switch x {
    case \"x\" {}
    case x {}
  }
}
", "
(function(){main=function(x){switch(x){case'x':break;case x:break}}})();
").jsMinify

# Check complex post-keyword space removal
test("
@export
def main(x int) int {
  if x == -1 { dynamic.foo() }
  else { dynamic.bar() }
  return 0
}
", "
(function(){main=function(a){return~a?bar():foo(),0}})();
").jsMinify.jsMangle

# Check nested negation minification
test("
@export
def main(x double) double {
  return x - (-x) * 2 + x + (-x) * 2
}
", "
(function(){main=function(x){return x- -x*2+x+-x*2}})();
").jsMinify

# Check nested negation minification
test("
@export
def main(x double) double {
  return x - (-2) * 2 + x + (-2) * 2
}
", "
(function(){main=function(x){return x- -4+x+-4}})();
").jsMinify.foldAllConstants

# Remove the space before the "in" operator
test("
@export
def test {
  dynamic.foo(dynamic.x in dynamic.y)
  dynamic.foo(\"x\" in dynamic.y)
}
", "
(function(){test=function(){foo(x in y);foo('x'in y)}})();
").jsMinify

  }
}
