testJS("
void foo() {}
var bar = foo;
", "
function foo() {
}
var bar = foo;
");

testJS("
class Foo {
  void foo() {}
}
Foo().foo();
", "
function Foo() {
}
Foo.prototype.foo = function() {
};
new Foo().foo();
");

testJS("
class Foo {
  Foo foo;
  void bar() {
    foo.bar();
  }
}
", "
function Foo(_0) {
  this.foo = _0;
}
Foo.prototype.bar = function() {
  this.foo.bar();
};
");

testJS("
(void fn())(=>);
", "
(function() {
});
");

testJS("
((void fn())=>)();
", "
(function() {
})();
");

testJS("
void fn() foo = =>;
", "
var foo = function() {
};
");

testJS("
void foo(int foo) {}
foo((1, 2));
", "
function foo(foo) {
}
foo((1, 2));
");

testJS("
class Foo {
  void foo() {}
}
var foo = Foo().foo;
", "
function Foo() {
}
Foo.prototype.foo = function() {
};
var foo = function($temp) {
  return $temp.foo.bind($temp);
}(new Foo());
");

testJS("
class Foo {
  void foo() {}
  export void fn() bar() { return foo; }
}
", "
function Foo() {
}
Foo.prototype.foo = function() {
};
Foo.prototype.bar = function() {
  return this.foo.bind(this);
};
");

testJS("
class Foo {
  static void foo() {}
}
var foo = Foo.foo;
", "
function Foo() {
}
Foo.foo = function() {
};
var foo = Foo.foo;
");

testJS("
enum Foo { A, B, C }
in Foo {
  int foo() {
    return this;
  }
}
Foo.A.foo();
", "
var Foo = {
  A: 0,
  B: 1,
  C: 2
};
Foo.foo = function($this) {
  return $this;
};
Foo.foo(Foo.A);
");

testJS("
enum Foo { FOO }
in Foo {
  export string foo() { return toString(); }
}
", "
var Foo = {
  FOO: 0
};
Foo.foo = function($this) {
  return Foo.toString($this);
};
Foo.toString = function($this) {
  switch ($this) {
  case 0:
    return \"FOO\";
  default:
    return \"\";
  }
};
");

testJS("
import class Foo {
  int x;
  new();
  int foo(Foo foo) {
    return x + foo.x;
  }
}
var foo = Foo().foo(Foo());
var bar = Foo().foo;
var baz = let _ = Foo() in _.foo;
", "
TODO
");
