testJS("
double x = 0;
- -1;
+ +1;
- +1;
+ -1;
- --x;
+ ++x;
- ++x;
+ --x;
", "
var x = 0;
- -1;
+ +1;
-+1;
+-1;
- --x;
+ ++x;
-++x;
+--x;
");

testJS("
double x = 0;
(1.0 - 2.0) - 3.0;
(1.0 / 2.0) * 3.0;
1.0 - (2.0 - 3.0);
1.0 / (2.0 * 3.0);
x = (x = x);
", "
var x = 0;
1 - 2 - 3;
1 / 2 * 3;
1 - (2 - 3);
1 / (2 * 3);
x = x = x;
");

testJS("
(bool)1;
(int)false;
(float)false;
", "
!1;
false | 0;
+false;
");

testJS("
assert (bool)1;
", "
if (1) {
  throw new Error(\"assert (bool)1; (<stdin>:1:1)\");
}
");

testJS("
void foo(bool foo) {
  (int)foo + 1;
  (int)foo - 1;
  (int)foo * 1;
  (int)foo / 1;
  (int)foo % 1;
  (int)foo | 1;
  (int)foo ^ 1;
  (int)foo & 1;
  (int)foo << 1;
  (int)foo >> 1;
  (int)foo, (int)true;
}
", "
function foo(foo) {
  (foo | 0) + 1 | 0;
  (foo | 0) - 1 | 0;
  (foo | 0) * 1 | 0;
  (foo | 0) / 1 | 0;
  (foo | 0) % 1 | 0;
  foo | 1;
  foo ^ 1;
  foo & 1;
  foo << 1;
  foo >> 1;
  foo | 0, true | 0;
}
");

testJS("
void foo(int foo) {
  foo + 1 | 1;
  foo - 1 | 1;
  foo * 1 | 1;
  foo / 1 | 1;
  foo % 1 | 1;
}
", "
function foo(foo) {
  foo + 1 | 1;
  foo - 1 | 1;
  foo * 1 | 1;
  foo / 1 | 1;
  foo % 1 | 1;
}
");

testJS("
void foo(int foo, bool bar) {
  foo += (int)bar;
  foo -= (int)bar;
  foo *= (int)bar;
  foo /= (int)bar;
  foo %= (int)bar;
  foo |= (int)bar;
  foo &= (int)bar;
  foo ^= (int)bar;
  foo <<= (int)bar;
  foo >>= (int)bar;
}
", "
function foo(foo, bar) {
  foo = foo + (bar | 0) | 0;
  foo = foo - (bar | 0) | 0;
  foo = foo * (bar | 0) | 0;
  foo = foo / (bar | 0) | 0;
  foo = foo % (bar | 0) | 0;
  foo |= bar;
  foo &= bar;
  foo ^= bar;
  foo <<= bar;
  foo >>= bar;
}
");

testJS("
void foo(int bar) {
  bar++, bar++;
  bar--, bar--;
  ++bar, ++bar;
  --bar, --bar;
  foo((bar++, bar++));
  foo((bar--, bar--));
  foo((++bar, ++bar));
  foo((--bar, --bar));
}
", "
function foo(bar) {
  bar = bar + 1 | 0, bar = bar + 1 | 0;
  bar = bar - 1 | 0, bar = bar - 1 | 0;
  bar = bar + 1 | 0, bar = bar + 1 | 0;
  bar = bar - 1 | 0, bar = bar - 1 | 0;
  foo((bar = bar + 1 | 0, (bar = bar + 1 | 0) - 1 | 0));
  foo((bar = bar - 1 | 0, (bar = bar - 1 | 0) + 1 | 0));
  foo((bar = bar + 1 | 0, bar = bar + 1 | 0));
  foo((bar = bar - 1 | 0, bar = bar - 1 | 0));
}
");

testJS("
class Foo {
  int bar;
  void foo(int foo) {
  }
  void baz() {
    bar++, bar++;
    bar--, bar--;
    ++bar, ++bar;
    --bar, --bar;
    foo((bar++, bar++));
    foo((bar--, bar--));
    foo((++bar, ++bar));
    foo((--bar, --bar));
  }
}
", "
function Foo(_0) {
  this.bar = _0;
}
Foo.prototype.foo = function(foo) {
};
Foo.prototype.baz = function() {
  this.bar = this.bar + 1 | 0, this.bar = this.bar + 1 | 0;
  this.bar = this.bar - 1 | 0, this.bar = this.bar - 1 | 0;
  this.bar = this.bar + 1 | 0, this.bar = this.bar + 1 | 0;
  this.bar = this.bar - 1 | 0, this.bar = this.bar - 1 | 0;
  this.foo((this.bar = this.bar + 1 | 0, (this.bar = this.bar + 1 | 0) - 1 | 0));
  this.foo((this.bar = this.bar - 1 | 0, (this.bar = this.bar - 1 | 0) + 1 | 0));
  this.foo((this.bar = this.bar + 1 | 0, this.bar = this.bar + 1 | 0));
  this.foo((this.bar = this.bar - 1 | 0, this.bar = this.bar - 1 | 0));
};
");

testJS("
int foo = (1, 2);
foo = (1, 2);
foo = 1, 2;
(1, 2), (3, 4);
", "
var foo = (1, 2);
foo = (1, 2);
foo = 1, 2;
(1, 2), (3, 4);
");
