namespace js { void testStatements() {

testJS("
import int foo;
", "
(function() {
}());
");

testJS("
int foo = 0;
class Foo {}
class Bar : Foo {}
", "
(function() {
}());
");

testJS("
class Foo {}
export class Bar : Foo {
  export void foo() {}
}
", "
(function() {
  function $extends(derived, base) {
    derived.prototype = Object.create(base.prototype);
    derived.prototype.constructor = derived;
  }
  function Foo() {
  }
  Bar = function() {
    Foo.call(this);
  };
  $extends(Bar, Foo);
  Bar.prototype.foo = function() {
  };
}());
");

testJS("
enum Foo { A, B, C }
export Foo foo() { return .A; }
export Foo bar() { return .C; }
", "
(function() {
  var Foo = {
    A: 0,
    C: 2
  };
  foo = function() {
    return Foo.A;
  };
  bar = function() {
    return Foo.C;
  };
}());
");

testJS("
export int foo(int x) {
  int y;
  switch (x) {
    case 1 { y = 1; }
    case 2 { y = 2; }
  }
  return y;
}
", "
(function() {
  foo = function(x) {
    var y = 0;
    switch (x) {
    case 1:
      y = 1;
      break;
    case 2:
      y = 2;
      break;
    }
    return y;
  };
}());
");

testJS("
interface IFoo {}
export class Foo<T is IFoo> {
  export T foo() {
    T foo;
    return foo;
  }
}
", "
(function() {
  Foo = function() {
  };
  Foo.prototype.foo = function() {
    var foo = null;
    return foo;
  };
}());
");

}}
