namespace core { void cyclic() {

test("
var foo = foo;
", "
<stdin>:1:5: error: Cyclic declaration of \"foo\"
var foo = foo;
    ~~~
");

test("
foo foo = foo;
", "
<stdin>:1:5: error: Cyclic declaration of \"foo\"
foo foo = foo;
    ~~~
");

test("
foo foo = foo, bar = bar;
", "
<stdin>:1:5: error: Cyclic declaration of \"foo\"
foo foo = foo, bar = bar;
    ~~~
");

test("
bar foo = foo, bar = bar;
", "
<stdin>:1:16: error: Cyclic declaration of \"bar\"
bar foo = foo, bar = bar;
               ~~~
");

test("
bar foo = foo;
foo bar = bar;
", "
<stdin>:1:5: error: Cyclic declaration of \"foo\"
bar foo = foo;
    ~~~
");

test("
class Foo : Foo {}
in Foo {}
", "
<stdin>:1:7: error: Cyclic declaration of \"Foo\"
class Foo : Foo {}
      ~~~
");

test("
in Foo {}
class Foo : Foo {}
", "
<stdin>:2:7: error: Cyclic declaration of \"Foo\"
class Foo : Foo {}
      ~~~
");

test("
class Foo : Bar {}
class Bar : Foo {}
", "
<stdin>:1:7: error: Cyclic declaration of \"Foo\"
class Foo : Bar {}
      ~~~
");

test("
class Foo : Bar {}
class Bar : Baz {}
class Baz : Foo {}
", "
<stdin>:1:7: error: Cyclic declaration of \"Foo\"
class Foo : Bar {}
      ~~~
");

test("
class Foo<T is T> {}
", "
<stdin>:1:11: error: Cyclic declaration of \"T\"
class Foo<T is T> {}
          ^
");

test("
class Foo<A is B, B is A> {}
", "
<stdin>:1:11: error: Cyclic declaration of \"A\"
class Foo<A is B, B is A> {}
          ^
");

test("
class Foo<A is B, B is C, C is A> {}
", "
<stdin>:1:11: error: Cyclic declaration of \"A\"
class Foo<A is B, B is C, C is A> {}
          ^
");

test("
void foo(foo bar);
", "
<stdin>:1:6: error: Cyclic declaration of \"foo\"
void foo(foo bar);
     ~~~
");

test("
void foo(bar baz);
void bar(foo baz);
", "
<stdin>:1:6: error: Cyclic declaration of \"foo\"
void foo(bar baz);
     ~~~
");

test("
enum Foo { FOO = FOO }
", "
<stdin>:1:12: error: Cyclic declaration of \"FOO\"
enum Foo { FOO = FOO }
           ~~~
");

test("
enum Foo { FOO = BAR, BAR }
", "
<stdin>:1:12: error: Cyclic declaration of \"FOO\"
enum Foo { FOO = BAR, BAR }
           ~~~
");

test("
class A : C {}
in A { class B : C.D {} }
class C {}
in C { class D : A {} }
", "
");

test("
class A : C.D {}
in A { class B {} }
class C : A.B {}
in C { class D {} }
", "
<stdin>:1:7: error: Cyclic declaration of \"A\"
class A : C.D {}
      ^
");

test("
alias foo = foo;
alias bar = baz;
alias baz = bar;
", "
<stdin>:1:7: error: Cyclic declaration of \"foo\"
alias foo = foo;
      ~~~
<stdin>:2:7: error: Cyclic declaration of \"bar\"
alias bar = baz;
      ~~~
");

test("
const int foo = foo;
const int bar = baz;
const int baz = bar;
", "
<stdin>:1:11: error: Cyclic declaration of \"foo\"
const int foo = foo;
          ~~~
<stdin>:2:11: error: Cyclic declaration of \"bar\"
const int bar = baz;
          ~~~
");

}}
