test("
int foo;
enum Foo { FOO = foo }
", "
<stdin>:2:18: error: Expected integer constant but found expression of type \"int\"
enum Foo { FOO = foo }
                 ~~~
");

test("
namespace foo {
  enum Foo { FOO = false }
}
", "
<stdin>:2:20: error: Cannot convert from type \"bool\" to type \"int\" without a cast
  enum Foo { FOO = false }
                   ~~~~~
");

test("
enum Foo { FOO }
enum flags Bar { FOO }
bool foo = Foo.FOO | Foo.FOO;
bool bar = Bar.FOO | Bar.FOO;
", "
<stdin>:3:12: error: Cannot convert from type \"int\" to type \"bool\" without a cast
bool foo = Foo.FOO | Foo.FOO;
           ~~~~~~~~~~~~~~~~~
<stdin>:4:12: error: Cannot convert from type \"Bar\" to type \"bool\" without a cast
bool bar = Bar.FOO | Bar.FOO;
           ~~~~~~~~~~~~~~~~~
");
