namespace core { void testFunctions() {

test("
import int foo();
import int bar() {}
", "
<stdin>:2:18: error: Imported functions cannot have an implementation
import int bar() {}
                 ~~
<stdin>:2:12: error: All control paths for \"bar\" must return a value of type \"int\"
import int bar() {}
           ~~~
");

test("
int foo() {}
void bar() {}
", "
<stdin>:1:5: error: All control paths for \"foo\" must return a value of type \"int\"
int foo() {}
    ~~~
");

test("
int foo(bool bar) {
  if (bar) return 0;
}
", "
<stdin>:1:5: error: All control paths for \"foo\" must return a value of type \"int\"
int foo(bool bar) {
    ~~~
");

test("
int foo(bool bar) {
  if (bar) return 0;
  else {}
}
", "
<stdin>:1:5: error: All control paths for \"foo\" must return a value of type \"int\"
int foo(bool bar) {
    ~~~
");

test("
int foo(bool bar) {
  if (bar) return 0;
  else if (bar) return 0;
  else return 0;
}
", "
");

test("
int foo(int bar) {
  switch (bar) {
    case 0 { return 0; }
  }
}
", "
<stdin>:1:5: error: All control paths for \"foo\" must return a value of type \"int\"
int foo(int bar) {
    ~~~
");

test("
int foo(int bar) {
  switch (bar) {
    case 0 { return 0; }
    case 1 {}
  }
}
", "
<stdin>:1:5: error: All control paths for \"foo\" must return a value of type \"int\"
int foo(int bar) {
    ~~~
");

test("
int foo(int bar) {
  switch (bar) {
    case 0 { return 0; }
    default {}
  }
}
", "
<stdin>:1:5: error: All control paths for \"foo\" must return a value of type \"int\"
int foo(int bar) {
    ~~~
");

test("
int foo(int bar) {
  switch (bar) {
    case 0 { return 0; }
    default { if (bar < 5) return 1; }
  }
}
", "
<stdin>:1:5: error: All control paths for \"foo\" must return a value of type \"int\"
int foo(int bar) {
    ~~~
");

test("
int foo(int bar) {
  switch (bar) {
    case 0 { return 0; }
    default { if (bar < 5) return 1; else return 2; }
  }
}
", "
");

test("
int foo() {
  return 0;
  1;
}
", "
<stdin>:3:3: warning: Unused expression
  1;
  ^
");

test("
void foo();
", "
<stdin>:1:6: error: Use the \"import\" modifier to import functions
void foo();
     ~~~
");

test("
class Foo { void foo(); }
interface Baz { void foo(); }
", "
<stdin>:1:18: error: Abstract functions must use the \"virtual\" modifier
class Foo { void foo(); }
                 ~~~
<stdin>:2:22: error: Abstract functions must use the \"virtual\" modifier
interface Baz { void foo(); }
                     ~~~
");

test("
class Foo { virtual void foo(); }
interface Baz { virtual void foo(); }
", "
");

test("
import class A { new(); }
import class B { import new(); }
import class C { export new(); }
", "
<stdin>:2:18: error: Redundant modifier \"import\" inside an imported type
import class B { import new(); }
                 ~~~~~~
<stdin>:3:18: error: Cannot use the \"export\" modifier inside an imported type
import class C { export new(); }
                 ~~~~~~
");

test("
export class A { new(); }
export class B { import new(); }
export class C { export new(); }
", "
<stdin>:1:18: error: Every constructor must have an implementation
export class A { new(); }
                 ~~~
<stdin>:2:18: error: Cannot use the \"import\" modifier inside a non-imported type
export class B { import new(); }
                 ~~~~~~
<stdin>:2:25: error: Every constructor must have an implementation
export class B { import new(); }
                        ~~~
<stdin>:3:18: error: Redundant modifier \"export\" inside an exported type
export class C { export new(); }
                 ~~~~~~
<stdin>:3:25: error: Every constructor must have an implementation
export class C { export new(); }
                        ~~~
");

test("
import class Foo {
  new();
  void foo();
}
export void foo() {
  Foo();
}
", "
");

test("
import class Foo {}
in Foo { export void foo() {} }
", "
<stdin>:2:10: error: Cannot use the \"export\" modifier inside an imported type
in Foo { export void foo() {} }
         ~~~~~~
");

test("
import namespace Foo {}
in Foo { export void foo() {} }
", "
<stdin>:2:10: error: Cannot use the \"export\" modifier inside an imported type
in Foo { export void foo() {} }
         ~~~~~~
");

test("
class Foo {
  new() {}
}
class Bar : Foo {
  new() : super() {}
}
class Baz : Foo {
  new() { super(); }
}
", "
<stdin>:8:11: error: Cannot use \"super\" here
  new() { super(); }
          ~~~~~~~
");

test("
interface Foo {
  void foo() {}
}
", "
");

test("
interface Foo {
  virtual void foo() {}
}
", "
<stdin>:2:22: error: Virtual interface functions cannot have an implementation
  virtual void foo() {}
                     ~~
");

test("
in Foo {
  virtual void foo() {}
}
interface Foo {}
", "
<stdin>:2:22: error: Virtual interface functions cannot have an implementation
  virtual void foo() {}
                     ~~
");

}}
