namespace core { void testLet() {

test("
export void test() {
  int y = let x = x in x;
}
", "
<stdin>:2:19: error: \"x\" is not declared
  int y = let x = x in x;
                  ^
");

test("
export void test() {
  int y = let x = 1 in let x = x + 1 in x + 1;
}
", "
");

test("
export void test() {
  !let x = 0 in x;
}
", "
<stdin>:2:3: error: No unary operator ! for type \"int\"
  !let x = 0 in x;
  ~~~~~~~~~~~~~~~
");

test("
export void test() {
  bool fn() foo = let x = 0 in => x;
}
", "
<stdin>:2:35: error: Cannot convert from type \"int\" to type \"bool\" without a cast
  bool fn() foo = let x = 0 in => x;
                                  ^
");

}}
