test("
return;
in Foo { return; }
class Foo { return; }
struct Bar { return; }
interface Baz { return; }
", "
<stdin>:1:1: error: Cannot use this statement here
return;
~~~~~~~
<stdin>:2:10: error: Cannot use this statement here
in Foo { return; }
         ~~~~~~~
<stdin>:3:13: error: Cannot use this statement here
class Foo { return; }
            ~~~~~~~
<stdin>:4:14: error: Cannot use this statement here
struct Bar { return; }
             ~~~~~~~
<stdin>:5:17: error: Cannot use this statement here
interface Baz { return; }
                ~~~~~~~
");

test("
inline using bar = foo;
", "
<stdin>:1:8: error: Cannot use this statement here
inline using bar = foo;
       ~~~~~~~~~~~~~~~~
");

test("
void foo() { using bar = int; }
", "
");

test("
if (true) class Foo {}
if (true) struct Foo {}
if (true) interface Foo {}
", "
<stdin>:1:11: error: Cannot use this statement here
if (true) class Foo {}
          ~~~~~~~~~~~~
<stdin>:2:11: error: Cannot use this statement here
if (true) struct Foo {}
          ~~~~~~~~~~~~~
<stdin>:3:11: error: Cannot use this statement here
if (true) interface Foo {}
          ~~~~~~~~~~~~~~~~
");

test("
void foo() { void foo(); }
void bar() { void bar() {} }
", "
<stdin>:1:14: error: Cannot use this statement here
void foo() { void foo(); }
             ~~~~~~~~~~~
<stdin>:2:14: error: Cannot use this statement here
void bar() { void bar() {} }
             ~~~~~~~~~~~~~
");

test("
void fn() foo = => {
  void fn() bar() {
    return => {
      void baz() {}
    };
  }
};
", "
<stdin>:2:3: error: Cannot use this statement here
  void fn() bar() {
  ~~~~~~~~~~~~~~~~~
<stdin>:4:7: error: Cannot use this statement here
      void baz() {}
      ~~~~~~~~~~~~~
");

test("
void foo() {
  class Foo {}
  interface Bar {}
  struct Baz {}
}
", "
<stdin>:2:3: error: Cannot use this statement here
  class Foo {}
  ~~~~~~~~~~~~
<stdin>:3:3: error: Cannot use this statement here
  interface Bar {}
  ~~~~~~~~~~~~~~~~
<stdin>:4:3: error: Cannot use this statement here
  struct Baz {}
  ~~~~~~~~~~~~~
");

test("
class Foo { final int foo; }
struct Bar { final int foo; }
interface Baz { final int foo; }
", "
<stdin>:3:23: error: Cannot use this statement here
interface Baz { final int foo; }
                      ~~~~~~~~
");

test("
class Foo {}
in Foo {
  int a = 0;
  int b, foo;
  static int c = 0;
  static int d;
}
", "
<stdin>:4:7: error: Instance variables in extension blocks must be initialized
  int b, foo;
      ^
<stdin>:4:10: error: Instance variables in extension blocks must be initialized
  int b, foo;
         ~~~
");

test("
interface Foo {}
in Foo {
  int a = 0;
  int b;
  static int c = 0;
  static int d;
}
", "
<stdin>:3:3: error: Cannot use this statement here
  int a = 0;
  ~~~~~~~~~~
<stdin>:4:3: error: Cannot use this statement here
  int b;
  ~~~~~~
");

test("
struct Foo {}
in Foo {
  final int a = 0;
  final int b, foo;
  static int c = 0;
  static int d;
}
", "
<stdin>:4:13: error: Instance variables in extension blocks must be initialized
  final int b, foo;
            ^
<stdin>:4:16: error: Instance variables in extension blocks must be initialized
  final int b, foo;
               ~~~
");

test("
enum Foo {}
in Foo {
  int a = 0;
  int b;
  static int c = 0;
  static int d;
}
", "
<stdin>:3:3: error: Cannot use this statement here
  int a = 0;
  ~~~~~~~~~~
<stdin>:4:3: error: Cannot use this statement here
  int b;
  ~~~~~~
");

test("
namespace Foo {}
in Foo {
  int a = 0;
  int b;
  static int c = 0;
  static int d;
}
", "
<stdin>:5:3: error: Cannot use the \"static\" modifier outside an object declaration
  static int c = 0;
  ~~~~~~
<stdin>:6:3: error: Cannot use the \"static\" modifier outside an object declaration
  static int d;
  ~~~~~~
");

test("
break; continue;
in Foo { break; continue; }
class Foo { break; continue; }
struct Bar { break; continue; }
interface Baz { break; continue; }
void foo() { break; continue; }
", "
<stdin>:1:1: error: Cannot use this statement here
break; continue;
~~~~~~
<stdin>:1:8: error: Cannot use this statement here
break; continue;
       ~~~~~~~~~
<stdin>:2:10: error: Cannot use this statement here
in Foo { break; continue; }
         ~~~~~~
<stdin>:2:17: error: Cannot use this statement here
in Foo { break; continue; }
                ~~~~~~~~~
<stdin>:3:13: error: Cannot use this statement here
class Foo { break; continue; }
            ~~~~~~
<stdin>:3:20: error: Cannot use this statement here
class Foo { break; continue; }
                   ~~~~~~~~~
<stdin>:4:14: error: Cannot use this statement here
struct Bar { break; continue; }
             ~~~~~~
<stdin>:4:21: error: Cannot use this statement here
struct Bar { break; continue; }
                    ~~~~~~~~~
<stdin>:5:17: error: Cannot use this statement here
interface Baz { break; continue; }
                ~~~~~~
<stdin>:5:24: error: Cannot use this statement here
interface Baz { break; continue; }
                       ~~~~~~~~~
<stdin>:6:14: error: Cannot use this statement here
void foo() { break; continue; }
             ~~~~~~
<stdin>:6:21: error: Cannot use this statement here
void foo() { break; continue; }
                    ~~~~~~~~~
");

test("
void foo() {
  break;
  while (true) {
    break;
    continue;
  }
  continue;
}
", "
<stdin>:2:3: error: Cannot use this statement here
  break;
  ~~~~~~
<stdin>:7:3: error: Cannot use this statement here
  continue;
  ~~~~~~~~~
");

test("
void foo() {
  while (true) {
    break;
    void fn() foo = => {
      break;
      while (true) {
        break;
        continue;
      }
      continue;
    };
    continue;
  }
}
", "
<stdin>:5:7: error: Cannot use this statement here
      break;
      ~~~~~~
<stdin>:10:7: error: Cannot use this statement here
      continue;
      ~~~~~~~~~
");

test("
break;
while (true) {
  break;
  while (true) {
    break;
    continue;
  }
  continue;
}
continue;
", "
<stdin>:1:1: error: Cannot use this statement here
break;
~~~~~~
<stdin>:10:1: error: Cannot use this statement here
continue;
~~~~~~~~~
");

test("
class Foo {
  assert true;
  for (;;) {}
  if (false) {}
  while (false) {}
  do {} while (false);
  switch (0) {}
  0;
}
", "
<stdin>:2:3: error: Cannot use this statement here
  assert true;
  ~~~~~~~~~~~~
<stdin>:3:3: error: Cannot use this statement here
  for (;;) {}
  ~~~~~~~~~~~
<stdin>:4:3: error: Cannot use this statement here
  if (false) {}
  ~~~~~~~~~~~~~
<stdin>:5:3: error: Cannot use this statement here
  while (false) {}
  ~~~~~~~~~~~~~~~~
<stdin>:6:3: error: Cannot use this statement here
  do {} while (false);
  ~~~~~~~~~~~~~~~~~~~~
<stdin>:7:3: error: Cannot use this statement here
  switch (0) {}
  ~~~~~~~~~~~~~
<stdin>:8:3: error: Cannot use this statement here
  0;
  ~~
<stdin>:8:3: warning: Unused expression
  0;
  ^
");

test("
void foo() {}
foo;
foo();
1, 2;
true ? 1 : 2;
", "
<stdin>:2:1: warning: Unused expression
foo;
~~~
<stdin>:4:1: warning: Unused expression
1, 2;
^
<stdin>:4:4: warning: Unused expression
1, 2;
   ^
<stdin>:5:8: warning: Unused expression
true ? 1 : 2;
       ^
<stdin>:5:12: warning: Unused expression
true ? 1 : 2;
           ^
");

test("
int i;
i++;
--i;
i = 1;
i *= 2;
", "
");

test("
void foo() {
  enum Foo { FOO }
}
", "
<stdin>:2:3: error: Cannot use this statement here
  enum Foo { FOO }
  ~~~~~~~~~~~~~~~~
");

test("
int foo() {}
void bar() {}
", "
<stdin>:1:5: error: All control paths for \"foo\" must return a value of type \"int\"
int foo() {}
    ~~~
");

test("
int foo(bool bar) {
  if (bar) return 0;
}
", "
<stdin>:1:5: error: All control paths for \"foo\" must return a value of type \"int\"
int foo(bool bar) {
    ~~~
");

test("
int foo(bool bar) {
  if (bar) return 0;
  else {}
}
", "
<stdin>:1:5: error: All control paths for \"foo\" must return a value of type \"int\"
int foo(bool bar) {
    ~~~
");

test("
int foo(bool bar) {
  if (bar) return 0;
  else if (bar) return 0;
  else return 0;
}
", "
");

test("
int foo(int bar) {
  switch (bar) {
    case 0 { return 0; }
  }
}
", "
<stdin>:1:5: error: All control paths for \"foo\" must return a value of type \"int\"
int foo(int bar) {
    ~~~
");

test("
int foo(int bar) {
  switch (bar) {
    case 0 { return 0; }
    case 1 {}
  }
}
", "
<stdin>:1:5: error: All control paths for \"foo\" must return a value of type \"int\"
int foo(int bar) {
    ~~~
");

test("
int foo(int bar) {
  switch (bar) {
    case 0 { return 0; }
    default {}
  }
}
", "
<stdin>:1:5: error: All control paths for \"foo\" must return a value of type \"int\"
int foo(int bar) {
    ~~~
");

test("
int foo(int bar) {
  switch (bar) {
    case 0 { return 0; }
    default { if (bar < 5) return 1; }
  }
}
", "
<stdin>:1:5: error: All control paths for \"foo\" must return a value of type \"int\"
int foo(int bar) {
    ~~~
");

test("
int foo(int bar) {
  switch (bar) {
    case 0 { return 0; }
    default { if (bar < 5) return 1; else return 2; }
  }
}
", "
");

test("
int fn() foo = =>;
int fn() bar = => 0;
", "
<stdin>:1:16: error: All control paths for lambda expression must return a value of type \"int\"
int fn() foo = =>;
               ~~
");

test("
int foo() {
  return 0;
  1;
}
", "
<stdin>:3:3: warning: Unused expression
  1;
  ^
");

test("
class Foo {
enum Bar {}
in Bar {
  void foo() { toString(); }
}
", "
<stdin>:5:2: error: Expected RIGHT_BRACE but found END_OF_FILE
}
 ^
<stdin>:2:1: error: Cannot use this statement here
enum Bar {}
~~~~~~~~~~~
<stdin>:3:1: error: Cannot use this statement here
in Bar {
~~~~~~~~
");
