namespace core { void testSwitch() {

test("
void test() {
  switch (0) {
    default {}
    case 1 {}
    default { foo }
    case 2 {}
    default {}
  }
}
", "
<stdin>:5:15: error: \"foo\" is not declared
    default { foo }
              ~~~
<stdin>:3:5: error: Only the last case can be a default case
    default {}
    ~~~~~~~~~~
<stdin>:5:5: error: Only the last case can be a default case
    default { foo }
    ~~~~~~~~~~~~~~~
")

test("
void test() {
  switch (0) {
    case 1 { foo }
    case 2, 3, 1, 1 { foo }
    case 1 { foo }
  }
}
", "
<stdin>:3:14: error: \"foo\" is not declared
    case 1 { foo }
             ~~~
<stdin>:4:23: error: \"foo\" is not declared
    case 2, 3, 1, 1 { foo }
                      ~~~
<stdin>:5:14: error: \"foo\" is not declared
    case 1 { foo }
             ~~~
<stdin>:4:16: error: Duplicate case value
    case 2, 3, 1, 1 { foo }
               ^
<stdin>:3:10: note: The first occurrence is here
    case 1 { foo }
         ^
<stdin>:4:19: error: Duplicate case value
    case 2, 3, 1, 1 { foo }
                  ^
<stdin>:3:10: note: The first occurrence is here
    case 1 { foo }
         ^
<stdin>:5:10: error: Duplicate case value
    case 1 { foo }
         ^
<stdin>:3:10: note: The first occurrence is here
    case 1 { foo }
         ^
")

test("
void test() {
  switch (0) {
    case false { foo }
    case false { foo }
  }
}
", "
<stdin>:3:10: error: Cannot convert from type \"bool\" to type \"int\" without a cast
    case false { foo }
         ~~~~~
<stdin>:3:18: error: \"foo\" is not declared
    case false { foo }
                 ~~~
<stdin>:4:10: error: Cannot convert from type \"bool\" to type \"int\" without a cast
    case false { foo }
         ~~~~~
<stdin>:4:18: error: \"foo\" is not declared
    case false { foo }
                 ~~~
")

test("
enum Foo { FOO, BAR, BAZ }
void foo(Foo foo) {
  switch (foo) {
    case .FOO, .BAR {}
    case .BAZ, .BAD {}
    case .FOO {}
  }
}
", "
<stdin>:5:17: error: \"BAD\" is not declared on type \"Foo\"
    case .BAZ, .BAD {}
                ~~~
<stdin>:6:10: error: Duplicate case value
    case .FOO {}
         ~~~~
<stdin>:4:10: note: The first occurrence is here
    case .FOO, .BAR {}
         ~~~~
")

test("
enum Foo { FOO, BAR = 0 }
void foo(Foo foo) {
  switch (foo) {
    case .FOO, .BAR {}
  }
}
", "
<stdin>:4:16: error: Duplicate case value
    case .FOO, .BAR {}
               ~~~~
<stdin>:4:10: note: The first occurrence is here
    case .FOO, .BAR {}
         ~~~~
")

test("
enum Foo { FOO }
void foo(int foo) {
  switch (foo) {
    case 0, Foo.FOO {}
  }
}
", "
<stdin>:4:13: error: Duplicate case value
    case 0, Foo.FOO {}
            ~~~~~~~
<stdin>:4:10: note: The first occurrence is here
    case 0, Foo.FOO {}
         ^
")

}}
