namespace core { void types() {

test("
void test() {
  (void)null;
}
", "
<stdin>:2:4: error: Cannot use type \"void\" here
  (void)null;
   ~~~~
");

test("
void test() {
  (ns)null;
}
namespace ns {}
", "
<stdin>:2:4: error: Cannot use type \"ns\" here
  (ns)null;
   ~~
");

test("
void foo;
", "
<stdin>:1:1: error: Cannot use type \"void\" here
void foo;
~~~~
");

test("
ns foo;
namespace ns {}
", "
<stdin>:1:1: error: Cannot use type \"ns\" here
ns foo;
~~
");

test("
void foo() {}
", "
");

test("
void fn() foo;
", "
");

test("
void fn(void, void) foo;
", "
<stdin>:1:9: error: Cannot use type \"void\" here
void fn(void, void) foo;
        ~~~~
<stdin>:1:15: error: Cannot use type \"void\" here
void fn(void, void) foo;
              ~~~~
");

test("
ns foo(ns bar, ns baz) {}
namespace ns {}
", "
<stdin>:1:1: error: Cannot use type \"ns\" here
ns foo(ns bar, ns baz) {}
~~
<stdin>:1:8: error: Cannot use type \"ns\" here
ns foo(ns bar, ns baz) {}
       ~~
<stdin>:1:16: error: Cannot use type \"ns\" here
ns foo(ns bar, ns baz) {}
               ~~
");

}}
