<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>sk</string>
  </array>
  <key>name</key>
  <string>Skew</string>
  <key>scopeName</key>
  <string>source.skew</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>match</key>
      <string>#.*</string>
      <key>name</key>
      <string>comment.skew</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(?:as|break|case|continue|default|else|finally|if|in|is|return|super|switch|throw|try|while)\b</string>
      <key>name</key>
      <string>keyword.skew</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(?:[A-Z_][A-Z0-9_]+|null|true|false|self|0b[01]+(?:\.[01]+)?|0o[0-7]+(?:\.[0-7]+)?|0x[0-9A-Fa-f]+(?:\.[0-9A-Fa-f]+)?|[0-9]+(?:\.[0-9]+)?(?:e[+-]?[0-9]+)?f?)\b</string>
      <key>name</key>
      <string>constant.numeric.skew</string>
    </dict>
    <dict>
      <key>match</key>
      <string>@[A-Za-z_][A-Za-z0-9_]*\b</string>
      <key>name</key>
      <string>keyword.skew</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(?:bool|double|dynamic|fn|int|string|[A-Z][A-Za-z0-9_]*(?:\.[A-Z][A-Za-z0-9_]*[a-z][A-Za-z0-9_]*)*)\b(?:&lt;.*?&gt;(?!&gt;))?</string>
      <key>name</key>
      <string>storage.type.skew</string>
    </dict>
    <dict>
      <key>match</key>
      <string>\bdef\b(?:\s+([A-Za-z0-9_\-\+\*/%!^&amp;|~=&gt;&lt;\[\]\{\}\.]+))?</string>
      <key>name</key>
      <string>keyword.skew</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.name.function.skew</string>
        </dict>
      </dict>
    </dict>
    <dict>
      <key>match</key>
      <string>\b(?:catch|class|const|enum|for|interface|namespace|over|var)\b(?:\s+([A-Za-z0-9_\.]+))?</string>
      <key>name</key>
      <string>keyword.skew</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.name.function.skew</string>
        </dict>
      </dict>
    </dict>
    <dict>
      <key>match</key>
      <string>^\s*\btype\b(?:\s+([A-Za-z0-9_\.]+))?</string>
      <key>name</key>
      <string>keyword.skew</string>
      <key>captures</key>
      <dict>
        <key>1</key>
        <dict>
          <key>name</key>
          <string>entity.name.function.skew</string>
        </dict>
      </dict>
    </dict>
    <dict>
      <key>begin</key>
      <string>'</string>
      <key>end</key>
      <string>'</string>
      <key>name</key>
      <string>string.quoted.single.skew</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\\.</string>
          <key>name</key>
          <string>constant.character.escape.skew</string>
        </dict>
      </array>
    </dict>
    <dict>
      <key>begin</key>
      <string>"</string>
      <key>end</key>
      <string>"</string>
      <key>name</key>
      <string>string.quoted.double.skew</string>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\\.</string>
          <key>name</key>
          <string>constant.character.escape.skew</string>
        </dict>
      </array>
    </dict>
  </array>
</dict>
</plist>
