namespace skew {
  var input = dynamic.document.getElementById("input")
  var output = dynamic.document.getElementById("output")

  def update {
    var log = Log.new
    var source = Source.new("<stdin>", input.value)
    var options = CompilerOptions.new
    var result = compile(log, options, [source])
    output.value = log.hasErrors ? log.toString : result.outputs.first.contents
  }

  @entry
  def main {
    input.oninput = => update
    update
  }
}
