def print(text string)

@entry
def mandelbrotFractal {
  var shades = " .-:;+=xX$& "
  var limit = shades.count - 1

  for row in 0..24 {
    var r = row / 12.0 - 1
    var line = ""

    for col in 0..80 {
      var c = col / 30.0 - 2
      var x = 0.0
      var y = 0.0
      var i = 0

      while i < limit && x * x + y * y < 4 {
        var temp = x * x - y * y + c
        y = 2 * x * y + r
        x = temp
        i += 1
      }

      line += shades.get(i)
    }

    print(line)
  }
}
