test("
int a = 0;
int b = false;
int c = 0.0f;
int d = 0.0;
int e = null;
int f = \"\";
", "
<stdin>:2:9: error: Cannot convert from type \"bool\" to type \"int\" without a cast
int b = false;
        ~~~~~
<stdin>:3:9: error: Cannot convert from type \"float\" to type \"int\" without a cast
int c = 0.0f;
        ~~~~
<stdin>:4:9: error: Cannot convert from type \"double\" to type \"int\" without a cast
int d = 0.0;
        ~~~
<stdin>:5:9: error: Cannot convert from type \"null\" to type \"int\"
int e = null;
        ~~~~
<stdin>:6:9: error: Cannot convert from type \"string\" to type \"int\"
int f = \"\";
        ~~
");

test("
bool a = 0;
bool b = false;
bool c = 0.0f;
bool d = 0.0;
bool e = null;
bool f = \"\";
", "
<stdin>:1:10: error: Cannot convert from type \"int\" to type \"bool\" without a cast
bool a = 0;
         ^
<stdin>:3:10: error: Cannot convert from type \"float\" to type \"bool\" without a cast
bool c = 0.0f;
         ~~~~
<stdin>:4:10: error: Cannot convert from type \"double\" to type \"bool\" without a cast
bool d = 0.0;
         ~~~
<stdin>:5:10: error: Cannot convert from type \"null\" to type \"bool\"
bool e = null;
         ~~~~
<stdin>:6:10: error: Cannot convert from type \"string\" to type \"bool\"
bool f = \"\";
         ~~
");

test("
float a = 0;
float b = false;
float c = 0.0f;
float d = 0.0;
float e = null;
float f = \"\";
", "
<stdin>:1:11: error: Cannot convert from type \"int\" to type \"float\" without a cast
float a = 0;
          ^
<stdin>:2:11: error: Cannot convert from type \"bool\" to type \"float\" without a cast
float b = false;
          ~~~~~
<stdin>:4:11: error: Cannot convert from type \"double\" to type \"float\" without a cast
float d = 0.0;
          ~~~
<stdin>:5:11: error: Cannot convert from type \"null\" to type \"float\"
float e = null;
          ~~~~
<stdin>:6:11: error: Cannot convert from type \"string\" to type \"float\"
float f = \"\";
          ~~
");

test("
double a = 0;
double b = false;
double c = 0.0f;
double d = 0.0;
double e = null;
double f = \"\";
", "
<stdin>:2:12: error: Cannot convert from type \"bool\" to type \"double\" without a cast
double b = false;
           ~~~~~
<stdin>:5:12: error: Cannot convert from type \"null\" to type \"double\"
double e = null;
           ~~~~
<stdin>:6:12: error: Cannot convert from type \"string\" to type \"double\"
double f = \"\";
           ~~
");

test("
string a = 0;
string b = false;
string c = 0.0f;
string d = 0.0;
string e = null;
string f = \"\";
", "
<stdin>:1:12: error: Cannot convert from type \"int\" to type \"string\"
string a = 0;
           ^
<stdin>:2:12: error: Cannot convert from type \"bool\" to type \"string\"
string b = false;
           ~~~~~
<stdin>:3:12: error: Cannot convert from type \"float\" to type \"string\"
string c = 0.0f;
           ~~~~
<stdin>:4:12: error: Cannot convert from type \"double\" to type \"string\"
string d = 0.0;
           ~~~
<stdin>:5:12: error: Cannot convert from type \"null\" to type \"string\"
string e = null;
           ~~~~
");

test("
int a = (int)0;
int b = (int)false;
int c = (int)0.0f;
int d = (int)0.0;
int e = (int)null;
int f = (int)\"\";
", "
<stdin>:5:14: error: Cannot convert from type \"null\" to type \"int\"
int e = (int)null;
             ~~~~
<stdin>:6:14: error: Cannot convert from type \"string\" to type \"int\"
int f = (int)\"\";
             ~~
");

test("
bool a = (bool)0;
bool b = (bool)false;
bool c = (bool)0.0f;
bool d = (bool)0.0;
bool e = (bool)null;
bool f = (bool)\"\";
", "
<stdin>:5:16: error: Cannot convert from type \"null\" to type \"bool\"
bool e = (bool)null;
               ~~~~
<stdin>:6:16: error: Cannot convert from type \"string\" to type \"bool\"
bool f = (bool)\"\";
               ~~
");

test("
float a = (float)0;
float b = (float)false;
float c = (float)0.0f;
float d = (float)0.0;
float e = (float)null;
float f = (float)\"\";
", "
<stdin>:5:18: error: Cannot convert from type \"null\" to type \"float\"
float e = (float)null;
                 ~~~~
<stdin>:6:18: error: Cannot convert from type \"string\" to type \"float\"
float f = (float)\"\";
                 ~~
");

test("
double a = (double)0;
double b = (double)false;
double c = (double)0.0f;
double d = (double)0.0;
double e = (double)null;
double f = (double)\"\";
", "
<stdin>:5:20: error: Cannot convert from type \"null\" to type \"double\"
double e = (double)null;
                   ~~~~
<stdin>:6:20: error: Cannot convert from type \"string\" to type \"double\"
double f = (double)\"\";
                   ~~
");

test("
string a = (string)0;
string b = (string)false;
string c = (string)0.0f;
string d = (string)0.0;
string e = (string)null;
string f = (string)\"\";
", "
<stdin>:1:20: error: Cannot convert from type \"int\" to type \"string\"
string a = (string)0;
                   ^
<stdin>:2:20: error: Cannot convert from type \"bool\" to type \"string\"
string b = (string)false;
                   ~~~~~
<stdin>:3:20: error: Cannot convert from type \"float\" to type \"string\"
string c = (string)0.0f;
                   ~~~~
<stdin>:4:20: error: Cannot convert from type \"double\" to type \"string\"
string d = (string)0.0;
                   ~~~
<stdin>:5:20: error: Cannot convert from type \"null\" to type \"string\"
string e = (string)null;
                   ~~~~
");

test("
int x = true ? true : false;
", "
<stdin>:1:9: error: Cannot convert from type \"bool\" to type \"int\" without a cast
int x = true ? true : false;
        ~~~~~~~~~~~~~~~~~~~
");

test("
bool x = true ? 0 : 1.0f;
", "
<stdin>:1:10: error: Cannot convert from type \"double\" to type \"bool\" without a cast
bool x = true ? 0 : 1.0f;
         ~~~~~~~~~~~~~~~
");

test("
int x = true ? 1 : false;
", "
<stdin>:1:16: error: No common type for type \"int\" and type \"bool\"
int x = true ? 1 : false;
               ~~~~~~~~~
");

test("
enum Foo { BAR, BAZ }
Foo x = true ? .BAR : .BAZ;
Foo y = .FOO;
", "
<stdin>:3:10: error: \"FOO\" is not declared on type \"Foo\"
Foo y = .FOO;
         ~~~
");

test("
class Foo {
  void baz() {
    int x = this;
  }
}
", "
<stdin>:3:13: error: Cannot convert from type \"Foo\" to type \"int\"
    int x = this;
            ~~~~
");

test("
enum Foo { FOO = false }
", "
<stdin>:1:18: error: Cannot convert from type \"bool\" to type \"Foo\" without a cast
enum Foo { FOO = false }
                 ~~~~~
");

test("
assert 0;
", "
<stdin>:1:8: error: Cannot convert from type \"int\" to type \"bool\" without a cast
assert 0;
       ^
");
