test("
in Foo {}
class Foo {}
", "
");

test("
in Foo {}
struct Foo {}
", "
");

test("
in Foo {}
interface Foo {}
", "
");

test("
in Foo {}
namespace Foo {}
", "
");

test("
in Foo {}
enum Foo {}
", "
");

test("
in Foo {}
enum flags Foo {}
", "
");

test("
int foo;
in foo {}
", "
<stdin>:2:4: error: \"foo\" is already declared
in foo {}
   ~~~
<stdin>:1:5: note: Previous declaration is here
int foo;
    ~~~
");

test("
in foo {}
int foo;
", "
<stdin>:2:5: error: \"foo\" is already declared
int foo;
    ~~~
<stdin>:1:4: note: Previous declaration is here
in foo {}
   ~~~
<stdin>:1:4: error: No type named \"foo\" to extend
in foo {}
   ~~~
");

test("
in foo {}
int foo() {}
", "
<stdin>:2:5: error: \"foo\" is already declared
int foo() {}
    ~~~
<stdin>:1:4: note: Previous declaration is here
in foo {}
   ~~~
<stdin>:1:4: error: No type named \"foo\" to extend
in foo {}
   ~~~
");

test("
namespace Foo {}
namespace Foo {}
", "
");

test("
class Foo {}
class Foo {}
", "
<stdin>:2:7: error: \"Foo\" is already declared
class Foo {}
      ~~~
<stdin>:1:7: note: Previous declaration is here
class Foo {}
      ~~~
");

test("
class Foo {}
struct Foo {}
", "
<stdin>:2:8: error: \"Foo\" is already declared
struct Foo {}
       ~~~
<stdin>:1:7: note: Previous declaration is here
class Foo {}
      ~~~
");

test("
struct Foo {}
interface Foo {}
", "
<stdin>:2:11: error: \"Foo\" is already declared
interface Foo {}
          ~~~
<stdin>:1:8: note: Previous declaration is here
struct Foo {}
       ~~~
");

test("
in Foo {}
", "
<stdin>:1:4: error: No type named \"Foo\" to extend
in Foo {}
   ~~~
");

test("
in Foo {}
in Foo {}
", "
<stdin>:1:4: error: No type named \"Foo\" to extend
in Foo {}
   ~~~
");

test("
namespace Foo.Bar { class Baz {} }
namespace Foo.Bar { class Baz {} }
", "
<stdin>:2:27: error: \"Baz\" is already declared
namespace Foo.Bar { class Baz {} }
                          ~~~
<stdin>:1:27: note: Previous declaration is here
namespace Foo.Bar { class Baz {} }
                          ~~~
");

test("
namespace Foo { in Bar { class Baz {} } }
namespace Foo.Bar { class Baz {} }
", "
<stdin>:2:27: error: \"Baz\" is already declared
namespace Foo.Bar { class Baz {} }
                          ~~~
<stdin>:1:32: note: Previous declaration is here
namespace Foo { in Bar { class Baz {} } }
                               ~~~
");

test("
import class Foo {}
export in Foo {}
", "
<stdin>:2:11: error: Cannot merge multiple declarations for \"Foo\" with different modifiers
export in Foo {}
          ~~~
<stdin>:1:14: note: Conflicting declaration is here
import class Foo {}
             ~~~
");

test("
class Foo<T> {}
int T;
", "
");

test("
class Foo<T> {
  int T;
}
", "
<stdin>:2:7: error: \"T\" is already declared
  int T;
      ^
<stdin>:1:11: note: Previous declaration is here
class Foo<T> {
          ^
");

test("
class Foo<T, T> {}
", "
<stdin>:1:14: error: \"T\" is already declared
class Foo<T, T> {}
             ^
<stdin>:1:11: note: Previous declaration is here
class Foo<T, T> {}
          ^
");
