test("
class Foo<T> : T {}
", "
<stdin>:1:16: error: Base type \"T\" must be an interface
class Foo<T> : T {}
               ^
");

test("
struct Foo : Bar {}
struct Bar {}
", "
<stdin>:1:14: error: A struct cannot inherit from another type
struct Foo : Bar {}
             ~~~
");

test("
interface IFoo {}
class Foo : IFoo, Bar {}
class Bar {}
", "
<stdin>:2:19: error: Base type \"Bar\" must come first in a class declaration
class Foo : IFoo, Bar {}
                  ~~~
");

test("
class Foo : Bar {}
class Bar {}
", "
");

test("
interface IFoo : IBar {}
interface IBar {}
", "
");

test("
interface IFoo : Bar {}
struct Bar {}
", "
<stdin>:1:18: error: Base type \"Bar\" must be an interface
interface IFoo : Bar {}
                 ~~~
");

test("
interface IFoo : Bar {}
class Bar {}
", "
<stdin>:1:18: error: Base type \"Bar\" must be an interface
interface IFoo : Bar {}
                 ~~~
");

test("
class Foo : IFoo, IFoo {}
interface IFoo {}
", "
<stdin>:1:19: error: Duplicate base type \"IFoo\"
class Foo : IFoo, IFoo {}
                  ~~~~
");

test("
class Foo {}
in Foo : Bar {}
class Bar {}
", "
<stdin>:2:10: error: Base type \"Bar\" must come first in a class declaration
in Foo : Bar {}
         ~~~
");

test("
class Foo {}
in Foo : IFoo {}
in Foo : IFoo {}
interface IFoo {}
", "
<stdin>:3:10: error: Duplicate base type \"IFoo\"
in Foo : IFoo {}
         ~~~~
");

test("
class Foo : IBar {}
class Bar : Foo, IBar {}
interface IFoo {}
interface IBar : IFoo {}
", "
");

test("
class Foo<T> {
  T foo = 0;
}
Foo.T foo = 0;
", "
<stdin>:2:11: error: Cannot convert from type \"int\" to type \"T\"
  T foo = 0;
          ^
<stdin>:4:5: error: \"T\" is not declared on type \"Foo\"
Foo.T foo = 0;
    ^
");

test("
class Foo : Bar {}
in Foo { class Bar {} }
", "
<stdin>:1:13: error: \"Bar\" is not declared
class Foo : Bar {}
            ~~~
");
