test("
bool a = 0b1101;
bool b = 0xFF01;
bool c = 0o7071;
", "
<stdin>:1:10: error: Cannot convert from type \"int\" to type \"bool\" without a cast
bool a = 0b1101;
         ~~~~~~
<stdin>:2:10: error: Cannot convert from type \"int\" to type \"bool\" without a cast
bool b = 0xFF01;
         ~~~~~~
<stdin>:3:10: error: Cannot convert from type \"int\" to type \"bool\" without a cast
bool c = 0o7071;
         ~~~~~~
");

test("
bool a = 0b1102;
bool b = 0xFF0G;
bool c = 0o7078;
", "
<stdin>:1:15: error: Expected SEMICOLON but found INT_DECIMAL
bool a = 0b1102;
              ^
<stdin>:2:15: error: Expected SEMICOLON but found IDENTIFIER
bool b = 0xFF0G;
              ^
<stdin>:3:15: error: Expected SEMICOLON but found INT_DECIMAL
bool c = 0o7078;
              ^
<stdin>:1:10: error: Cannot convert from type \"int\" to type \"bool\" without a cast
bool a = 0b1102;
         ~~~~~
<stdin>:2:10: error: Cannot convert from type \"int\" to type \"bool\" without a cast
bool b = 0xFF0G;
         ~~~~~
<stdin>:3:10: error: Cannot convert from type \"int\" to type \"bool\" without a cast
bool c = 0o7078;
         ~~~~~
");

test("
bool a = 0b11.01;
bool b = 0xFF.01;
bool c = 0o70.71;
", "
<stdin>:1:15: error: Expected IDENTIFIER but found INT_DECIMAL
bool a = 0b11.01;
              ~~
<stdin>:2:15: error: Expected IDENTIFIER but found INT_DECIMAL
bool b = 0xFF.01;
              ~~
<stdin>:3:15: error: Expected IDENTIFIER but found INT_DECIMAL
bool c = 0o70.71;
              ~~
");

test("
bool a = 0b11.01f;
bool b = 0xFF.01f;
bool c = 0o70.71f;
", "
<stdin>:1:15: error: Expected IDENTIFIER but found FLOAT
bool a = 0b11.01f;
              ~~~
<stdin>:2:15: error: Expected IDENTIFIER but found FLOAT
bool b = 0xFF.01f;
              ~~~
<stdin>:3:15: error: Expected IDENTIFIER but found FLOAT
bool c = 0o70.71f;
              ~~~
");

test("
int x = (in)1.5;
", "
<stdin>:1:10: error: Unexpected IN
int x = (in)1.5;
         ~~
<stdin>:1:13: error: Expected SEMICOLON but found DOUBLE
int x = (in)1.5;
            ~~~
");

test("
int x = .
", "
<stdin>:1:10: error: Expected IDENTIFIER but found END_OF_FILE
int x = .
         ^
");

test("
int x = .;
", "
<stdin>:1:10: error: Expected IDENTIFIER but found SEMICOLON
int x = .;
         ^
");

test("
enum Foo { FOO }
Foo x = Foo.;
", "
<stdin>:2:13: error: Expected IDENTIFIER but found SEMICOLON
Foo x = Foo.;
            ^
");

test("
enum Foo { FOO }
Foo x = .FOO;
bool y = (Foo).FOO;
", "
<stdin>:3:10: error: Cannot convert from type \"Foo\" to type \"bool\" without a cast
bool y = (Foo).FOO;
         ~~~~~~~~~
");

test("
for (int x, y in z) {}
", "
<stdin>:1:6: error: More than one variable inside a for-each loop
for (int x, y in z) {}
     ~~~~~~~~
<stdin>:1:18: error: \"z\" is not declared
for (int x, y in z) {}
                 ^
");

test("
if
", "
<stdin>:1:3: error: Expected LEFT_PARENTHESIS but found END_OF_FILE
if
  ^
");

test("
while
", "
<stdin>:1:6: error: Expected LEFT_PARENTHESIS but found END_OF_FILE
while
     ^
");

test("
for
", "
<stdin>:1:4: error: Expected LEFT_PARENTHESIS but found END_OF_FILE
for
   ^
");

test("
do {} while
", "
<stdin>:1:12: error: Expected LEFT_PARENTHESIS but found END_OF_FILE
do {} while
           ^
");

test("
do {} while;
do {} while;
", "
<stdin>:1:12: error: Expected LEFT_PARENTHESIS but found SEMICOLON
do {} while;
           ^
<stdin>:2:12: error: Expected LEFT_PARENTHESIS but found SEMICOLON
do {} while;
           ^
");

test("
for (int x in
", "
<stdin>:1:14: error: Unexpected END_OF_FILE
for (int x in
             ^
");

test("
for (int x in) {}
", "
<stdin>:1:14: error: Unexpected RIGHT_PARENTHESIS
for (int x in) {}
             ^
");

test("
else
", "
<stdin>:1:1: error: Unexpected ELSE
else
~~~~
");

test("
if () {}
", "
<stdin>:1:5: error: Unexpected RIGHT_PARENTHESIS
if () {}
    ^
");

test("
void fn() a0 = =>;
bool fn() a1 = => false;
void fn() a2 = => {};
void fn() a3 = => { return; };

void fn() b0 = () =>;
bool fn() b1 = () => false;
void fn() b2 = () => {};
void fn() b3 = () => { return; };

void fn(int) c0 = x =>;
bool fn(int) c1 = x => false;
void fn(int) c2 = x => {};
void fn(int) c3 = x => { return; };

void fn(int) d0 = (x) =>;
bool fn(int) d1 = (x) => false;
void fn(int) d2 = (x) => {};
void fn(int) d3 = (x) => { return; };

void fn(int, int) e0 = (x, y) =>;
bool fn(int, int) e1 = (x, y) => false;
void fn(int, int) e2 = (x, y) => {};
void fn(int, int) e3 = (x, y) => { return; };
", "
");

test("
int fn(int, float) foo = null, bar = null;
", "
");

test("
int fn(int, float) fn(int fn(int, float), float fn(int, float)) foo = null, bar = null;
", "
");

test("
(int) fn(int, float) foo = null, bar = null;
", "
<stdin>:1:7: error: Unexpected FN
(int) fn(int, float) foo = null, bar = null;
      ~~
<stdin>:1:9: error: Expected SEMICOLON but found LEFT_PARENTHESIS
(int) fn(int, float) foo = null, bar = null;
        ^
<stdin>:1:20: error: Unexpected RIGHT_PARENTHESIS
(int) fn(int, float) foo = null, bar = null;
                   ^
");

test("
int fn(int x, float y) foo = null, bar = null;
", "
<stdin>:1:12: error: Expected COMMA but found IDENTIFIER
int fn(int x, float y) foo = null, bar = null;
           ^
");

test("
int. fn() foo = null, bar = null;
", "
<stdin>:1:6: error: Expected IDENTIFIER but found FN
int. fn() foo = null, bar = null;
     ~~
");

test("
100 fn() foo = null, bar = null;
", "
<stdin>:1:5: error: Unexpected FN
100 fn() foo = null, bar = null;
    ~~
<stdin>:1:7: error: Expected SEMICOLON but found LEFT_PARENTHESIS
100 fn() foo = null, bar = null;
      ^
<stdin>:1:8: error: Unexpected RIGHT_PARENTHESIS
100 fn() foo = null, bar = null;
       ^
");

test("
Foo<Bar Baz> foo;
Foo<Bar Baz> bar;
", "
<stdin>:1:9: error: Expected END_PARAMETER_LIST but found IDENTIFIER
Foo<Bar Baz> foo;
        ~~~
<stdin>:2:9: error: Expected END_PARAMETER_LIST but found IDENTIFIER
Foo<Bar Baz> bar;
        ~~~
");

test("
class Foo :
", "
<stdin>:1:12: error: Unexpected END_OF_FILE
class Foo :
           ^
");

test("
class Foo : Bar
", "
<stdin>:1:16: error: Expected LEFT_BRACE but found END_OF_FILE
class Foo : Bar
               ^
");

test("
class Foo : {}
class Bar : {}
", "
<stdin>:1:13: error: Unexpected LEFT_BRACE
class Foo : {}
            ^
<stdin>:2:13: error: Unexpected LEFT_BRACE
class Bar : {}
            ^
");

test("
class Foo : Bar, {}
class Bar : Baz, {}
", "
<stdin>:1:18: error: Unexpected LEFT_BRACE
class Foo : Bar, {}
                 ^
<stdin>:2:18: error: Unexpected LEFT_BRACE
class Bar : Baz, {}
                 ^
<stdin>:2:13: error: \"Baz\" is not declared
class Bar : Baz, {}
            ~~~
");

test("
switch (0) {
  case {}
  case 1, {}
  case 2, 3, {}
}
", "
<stdin>:2:8: error: Unexpected LEFT_BRACE
  case {}
       ^
<stdin>:3:11: error: Unexpected LEFT_BRACE
  case 1, {}
          ^
<stdin>:4:14: error: Unexpected LEFT_BRACE
  case 2, 3, {}
             ^
");
