test("
return;
in Foo { return; }
class Foo { return; }
struct Bar { return; }
interface Baz { return; }
", "
<stdin>:1:1: error: Cannot use this statement here
return;
~~~~~~~
<stdin>:2:10: error: Cannot use this statement here
in Foo { return; }
         ~~~~~~~
<stdin>:3:13: error: Cannot use this statement here
class Foo { return; }
            ~~~~~~~
<stdin>:4:14: error: Cannot use this statement here
struct Bar { return; }
             ~~~~~~~
<stdin>:5:17: error: Cannot use this statement here
interface Baz { return; }
                ~~~~~~~
");

test("
inline using bar = foo;
", "
<stdin>:1:8: error: Cannot use this statement here
inline using bar = foo;
       ~~~~~~~~~~~~~~~~
");

test("
void foo() { using bar = int; }
", "
");

test("
if (true) class Foo {}
if (true) struct Foo {}
if (true) interface Foo {}
", "
<stdin>:1:11: error: Cannot use this statement here
if (true) class Foo {}
          ~~~~~~~~~~~~
<stdin>:2:11: error: Cannot use this statement here
if (true) struct Foo {}
          ~~~~~~~~~~~~~
<stdin>:3:11: error: Cannot use this statement here
if (true) interface Foo {}
          ~~~~~~~~~~~~~~~~
");

test("
void foo() { void foo(); }
void bar() { void bar() {} }
", "
<stdin>:1:14: error: Cannot use this statement here
void foo() { void foo(); }
             ~~~~~~~~~~~
<stdin>:2:14: error: Cannot use this statement here
void bar() { void bar() {} }
             ~~~~~~~~~~~~~
");

test("
void foo() {
  class Foo {}
  interface Bar {}
  struct Baz {}
}
", "
<stdin>:2:3: error: Cannot use this statement here
  class Foo {}
  ~~~~~~~~~~~~
<stdin>:3:3: error: Cannot use this statement here
  interface Bar {}
  ~~~~~~~~~~~~~~~~
<stdin>:4:3: error: Cannot use this statement here
  struct Baz {}
  ~~~~~~~~~~~~~
");

test("
class Foo {}
in Foo {
  int a = 0;
  int b, foo;
  static int c = 0;
  static int d;
}
", "
<stdin>:4:3: error: Cannot use this statement here
  int b, foo;
  ~~~~~
<stdin>:4:10: error: Cannot use this statement here
  int b, foo;
         ~~~~
");

test("
interface Foo {}
in Foo {
  int a = 0;
  int b;
  static int c = 0;
  static int d;
}
", "
<stdin>:3:3: error: Cannot use this statement here
  int a = 0;
  ~~~~~~~~~~
<stdin>:4:3: error: Cannot use this statement here
  int b;
  ~~~~~~
");

test("
struct Foo {}
in Foo {
  int a = 0;
  int b;
  static int c = 0;
  static int d;
}
", "
<stdin>:3:3: error: Cannot use this statement here
  int a = 0;
  ~~~~~~~~~~
<stdin>:4:3: error: Cannot use this statement here
  int b;
  ~~~~~~
");

test("
enum Foo {}
in Foo {
  int a = 0;
  int b;
  static int c = 0;
  static int d;
}
", "
<stdin>:3:3: error: Cannot use this statement here
  int a = 0;
  ~~~~~~~~~~
<stdin>:4:3: error: Cannot use this statement here
  int b;
  ~~~~~~
");
