test("
switch (0) {
  default {}
  case 1 {}
  default { foo; }
  case 2 {}
  default {}
}
", "
<stdin>:2:3: error: Only the last case can be a default case
  default {}
  ~~~~~~~~~~
<stdin>:4:3: error: Only the last case can be a default case
  default { foo; }
  ~~~~~~~~~~~~~~~~
<stdin>:4:13: error: \"foo\" is not declared
  default { foo; }
            ~~~
");

test("
switch (0) {
  case 1 { foo; }
  case 2, 3, 1, 1 { foo; }
  case 1 { foo; }
}
", "
<stdin>:3:14: error: Duplicate case value here
  case 2, 3, 1, 1 { foo; }
             ^
<stdin>:2:8: note: First occurrence is here
  case 1 { foo; }
       ^
<stdin>:3:17: error: Duplicate case value here
  case 2, 3, 1, 1 { foo; }
                ^
<stdin>:2:8: note: First occurrence is here
  case 1 { foo; }
       ^
<stdin>:4:8: error: Duplicate case value here
  case 1 { foo; }
       ^
<stdin>:2:8: note: First occurrence is here
  case 1 { foo; }
       ^
<stdin>:2:12: error: \"foo\" is not declared
  case 1 { foo; }
           ~~~
<stdin>:3:21: error: \"foo\" is not declared
  case 2, 3, 1, 1 { foo; }
                    ~~~
<stdin>:4:12: error: \"foo\" is not declared
  case 1 { foo; }
           ~~~
");

test("
switch (0) {
  case false { foo; }
  case false { foo; }
}
", "
<stdin>:3:8: error: Duplicate case value here
  case false { foo; }
       ~~~~~
<stdin>:2:8: note: First occurrence is here
  case false { foo; }
       ~~~~~
<stdin>:2:8: error: Cannot convert from type \"bool\" to type \"int\" without a cast
  case false { foo; }
       ~~~~~
<stdin>:2:16: error: \"foo\" is not declared
  case false { foo; }
               ~~~
<stdin>:3:8: error: Cannot convert from type \"bool\" to type \"int\" without a cast
  case false { foo; }
       ~~~~~
<stdin>:3:16: error: \"foo\" is not declared
  case false { foo; }
               ~~~
");

test("
enum Foo { FOO, BAR, BAZ }
void foo(Foo foo) {
  switch (foo) {
    case .FOO, .BAR {}
    case .BAZ, .BAD {}
  }
}
", "
<stdin>:5:17: error: \"BAD\" is not declared on type \"Foo\"
    case .BAZ, .BAD {}
                ~~~
");
