test("
var foo;
", "
<stdin>:1:5: error: Implicitly typed variables must be initialized
var foo;
    ~~~
");

test("
var foo = bar;
int bar = foo;
", "
");

test("
var foo = 0;
bool bar = foo;
", "
<stdin>:2:12: error: Cannot convert from type \"int\" to type \"bool\" without a cast
bool bar = foo;
           ~~~
");

test("
var foo = null, bar = null;
", "
<stdin>:1:5: error: Implicitly typed variables cannot be of type \"null\"
var foo = null, bar = null;
    ~~~
<stdin>:1:17: error: Implicitly typed variables cannot be of type \"null\"
var foo = null, bar = null;
                ~~~
");

test("
var foo() {
  return 100;
}
", "
<stdin>:1:1: error: Unexpected VAR
var foo() {
~~~
");

test("
void foo(var bar) {}
", "
<stdin>:1:14: error: Implicitly typed variables must be initialized
void foo(var bar) {}
             ~~~
");

test("
var foo = bar();
void fn() bar = null;
", "
<stdin>:1:5: error: Implicitly typed variables cannot be of type \"void\"
var foo = bar();
    ~~~
");
